export { default as DesignIcon1 } from "./DesignIcon1";
export { default as DesignIcon2 } from "./DesignIcon2";
export { default as DesignIcon3 } from "./DesignIcon3";
export { default as DesignIcon4 } from "./DesignIcon4";
export { default as DesignIcon5 } from "./DesignIcon5";
export { default as DesignIcon6 } from "./DesignIcon6";
export { default as DesignIcon7 } from "./DesignIcon7";
export { default as DesignIcon8 } from "./DesignIcon8";
export { default as DesignIcon9 } from "./DesignIcon9";
export { default as DesignIcon10 } from "./DesignIcon10";
export { default as DesignIcon11 } from "./DesignIcon11";
export { default as DesignIcon12 } from "./DesignIcon12";
export { default as DesignIcon13 } from "./DesignIcon13";
export { default as DesignIcon14 } from "./DesignIcon14";
export { default as DesignIcon15 } from "./DesignIcon15";
export { default as DesignIcon16 } from "./DesignIcon16";
export { default as DesignIcon17 } from "./DesignIcon17";
export { default as DesignIcon18 } from "./DesignIcon18";
export { default as DesignIcon19 } from "./DesignIcon19";
export { default as DesignIcon20 } from "./DesignIcon20";
export { default as DesignIcon21 } from "./DesignIcon21";
export { default as DesignIcon22 } from "./DesignIcon22";
export { default as DesignIcon23 } from "./DesignIcon23";
export { default as DesignIcon24 } from "./DesignIcon24";
export { default as DesignIcon25 } from "./DesignIcon25";
export { default as DesignIcon26 } from "./DesignIcon26";
export { default as DesignIcon27 } from "./DesignIcon27";
export { default as DesignIcon28 } from "./DesignIcon28";
export { default as DesignIcon29 } from "./DesignIcon29";
export { default as DesignIcon30 } from "./DesignIcon30";
export { default as DesignIcon31 } from "./DesignIcon31";
export { default as DesignIcon32 } from "./DesignIcon32";
export { default as DesignIcon33 } from "./DesignIcon33";
export { default as DesignIcon34 } from "./DesignIcon34";
export { default as DesignIcon35 } from "./DesignIcon35";   
export { default as DesignIcon36 } from "./DesignIcon36";
export { default as DesignIcon37 } from "./DesignIcon37";
export { default as DesignIcon38 } from "./DesignIcon38";
export { default as DesignIcon39 } from "./DesignIcon39";
export { default as DesignIcon40 } from "./DesignIcon40";
export { default as DesignIcon41 } from "./DesignIcon41";
export { default as DesignIcon42 } from "./DesignIcon42";
export { default as DesignIcon43 } from "./DesignIcon43";
export { default as DesignIcon44 } from "./DesignIcon44";
export { default as DesignIcon45 } from "./DesignIcon45";
export { default as DesignIcon46 } from "./DesignIcon46";
export { default as DesignIcon47 } from "./DesignIcon47";
export { default as DesignIcon48 } from "./DesignIcon48";
export { default as DesignIcon49 } from "./DesignIcon49";
export { default as PhoneIcon } from "./PhoneIcon";
export { default as PhoneIcon2 } from "./PhoneIcon2";
export { default as MailIcon } from "./MailIcon";
export { default as EICIcon } from "./EICIcon";
export { default as FMIcon } from "./FMIcon";
export { default as ANTIcon } from "./ANTIcon";
export { default as AttestationIcon } from "./AttestationIcon";
export { default as HCIcon } from "./HCIcon";
export { default as IMIcon } from "./IMIcon";
export { default as InterHiringIcon } from "./InterHiringIcon";
export { default as LocalHiringIcon } from "./LocalHiringIcon";
export { default as LSCMIcon } from "./LSCMIcon";
export { default as OGEIcon } from "./OGEIcon";
export { default as QuotationIcon } from "./QuotationIcon";
export { default as RFBIcon } from "./RFBIcon";
export { default as CalendarIcon } from "./CalendarIcon";
export { default as LeftArrowIcon } from "./LeftArrowIcon";
export { default as LocationIcon } from "./LocationIcon";
export { default as LocationIcon2 } from "./LocationIcon2";
export { default as SearchIcon } from "./SearchIcon";
export { default as LiveChatIcon } from "./LiveChatIcon";
export { default as EmailIcon } from "./EmailIcon";
export { default as EmailIcon2 } from "./EmailIcon2";
export { default as PhoneIcon3 } from "./PhoneIcon3";
import StrategicSourcingIcon from "./Approach/StrategicSourcingIcon";
import QualityScreeningIcon from "./Approach/QualityScreeningIcon";
import StructuredInterviewsIcon from "./Approach/StructuredInterviewsIcon";
import SeamlessOnboardingIcon from "./Approach/SeamlessOnboardingIcon";
import DesignIcon50 from "./DesignIcon50";
import DesignIcon51 from "./DesignIcon51";
import DesignIcon52 from "./DesignIcon52";
import DesignIcon53 from "./DesignIcon53";
import DesignIcon54 from "./DesignIcon54";
import DesignIcon55 from "./DesignIcon55";
import DesignIcon56 from "./DesignIcon56";
import DesignIcon57 from "./DesignIcon57";
import DesignIcon58 from "./DesignIcon58";
import DesignIcon59 from "./DesignIcon59";
import DesignIcon60 from "./DesignIcon60";
import DesignIcon61 from "./DesignIcon61";
import DesignIcon62 from "./DesignIcon62";
import DoubleQuotesIcon from "./DoubleQuotesIcon";

export { DoubleQuotesIcon, StrategicSourcingIcon, QualityScreeningIcon, StructuredInterviewsIcon, SeamlessOnboardingIcon, DesignIcon50, DesignIcon51, DesignIcon52, DesignIcon53, DesignIcon54, DesignIcon55, DesignIcon56, DesignIcon57, DesignIcon58, DesignIcon59, DesignIcon60, DesignIcon61, DesignIcon62 };